services:
    rotorhazard:
        build: .
        restart: always
        volumes:
            - .:/RotorHazard
        ports:
            - "5000:5000"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.rotorhazard.rule=Host(`rotorhazard.docker.localhost`)"
            - "traefik.http.routers.rotorhazard.tls=true"
            - "traefik.http.services.rotorhazard.loadbalancer.server.port=5000"
        networks:
            - proxy

networks:
    proxy:
        external: true
