---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - obsidian:/config
    ports:
      - 9999:3000
      - 9998:3001
    #devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  obsidian:
